package cmd

import (
	"fmt"
	"os"
	"strings"

	"github.com/dave/jennifer/jen"
	"github.com/sirupsen/logrus"
	"github.com/spf13/cobra"
)

// Template migration command
var Template = &cobra.Command{
	Use:   "tpl",
	Short: "Generate templates",
	Long:  `Generate templates`,
	Run: func(cmd *cobra.Command, args []string) {
		createRegisterMigrationsCollection()

		createApplyCmd(cmd)

		logrus.Info("templates generated")
	},
}

func createRegisterMigrationsCollection() {
	dest := migrationsDest + "/registermigrations.go"

	if _, err := os.Stat(dest); os.IsNotExist(err) {
		m := jen.NewFile(migrationsDest)

		m.ImportAlias(gomigrateLib, "gomigrateCmd")

		printAutoGeneratedNote(m)

		m.Comment("Collection with all migrations")
		m.Var().Id("Collection").Op("=").Index().Qual(gomigrateLib, "MigrationDefinition").Block()

		c := []byte(fmt.Sprintf("%#v", m))

		writeFileContent(dest, c)
	}
}

func createApplyCmd(cmd *cobra.Command) {
	dest := cmdDest + "/migration.go"

	if _, err := os.Stat(dest); os.IsNotExist(err) {
		var pkg = cmd.Flag("pkg").Value.String()

		if strings.TrimSpace(pkg) == "" {
			logrus.Fatal("invalid github package url")
		}

		m := jen.NewFile(cmdDest)

		m.ImportAlias(gomigrateLib, "gomigrateCmd")

		printAutoGeneratedNote(m)

		m.Var().Id("config").Op("= &").Qual(gomigrateLib, "Config").Values(
			jen.Dict{
				jen.Id("Dialect"): jen.Lit("postgres"),
				jen.Id("ConnString"): jen.Qual("fmt", "Sprintf").
					Call(
						jen.Lit("host=%s port=%s dbname=%s user=%s password=%s sslmode=disable"),
						jen.Line().Qual(goDevLib+"/env", "Get").Call(jen.Lit("M_HOST"), jen.Lit("localhost")),
						jen.Line().Qual(goDevLib+"/env", "Get").Call(jen.Lit("M_PORT"), jen.Lit("5432")),
						jen.Line().Qual(goDevLib+"/env", "Get").Call(jen.Lit("M_DBNAME"), jen.Lit("db_name")),
						jen.Line().Qual(goDevLib+"/env", "Get").Call(jen.Lit("M_USER"), jen.Lit("postgres")),
						jen.Line().Qual(goDevLib+"/env", "Get").Call(jen.Lit("M_PASSWORD"), jen.Lit("postgres")),
					),
			},
		)

		m.Comment("Migration command")
		m.Var().Id("Migration").Op("= &").Qual(cobraLib, "Command").Values(
			jen.Dict{
				jen.Id("Use"):   jen.Lit(""),
				jen.Id("Short"): jen.Lit("Migrations tool"),
				jen.Id("Long"):  jen.Lit("`Migrations tool`"),
				jen.Id("Run"):   jen.Func().Params(jen.Id("cmd").Op("*").Qual(cobraLib, "Command"), jen.Id("agrs").Index().String()).Block(),
			},
		)

		m.Comment("Apply command")
		m.Var().Id("Apply").Op("= &").Qual(cobraLib, "Command").Values(
			jen.Dict{
				jen.Id("Use"):   jen.Lit("migrate"),
				jen.Id("Short"): jen.Lit("Apply migrations"),
				jen.Id("Long"):  jen.Lit("`Apply migrations`"),
				jen.Id("Run"): jen.Func().Params(jen.Id("cmd").Op("*").Qual(cobraLib, "Command"), jen.Id("agrs").Index().String()).Block(
					jen.Qual(gomigrateLib, "Run").Call(jen.Qual("github.com/"+pkg+"/"+migrationsDest, "Collection"), jen.Id("config")),
					jen.Qual(logrusLib, "Info").Call(jen.Lit("migrations script finished")),
				),
			},
		)

		m.Func().Id("init").Params().Block(
			jen.Qual("", "Migration.AddCommand").Call(jen.Id("Apply")),
		)

		c := []byte(fmt.Sprintf("%#v", m))

		writeFileContent(dest, c)
	}
}
